### ISSUE TITLE
Add a `direnv` health check (flake-specific)

### ISSUE THREAD

**Issue by srid** [srid/nix-health#4]
This check should be disabled by default, and only enabled when `nix-health.default.direnv.enable = true;` is in the flake (per #60).

It should check:
- `direnv` is in PATH, else point to https://zero-to-flakes.com/direnv/
- `direnv status` contains `Found RC allowed true`, else ask the user to run `direnv allow`

**Comment by shivaraj-bh** [comment]
Is it possible to also check if `direnv allow` has been run for the respective project/repo?

**Comment by shivaraj-bh** [comment]
I can parse the output of `direnv status` to check if direnv is allowed on the current directory but the check for `IN_NIX_SHELL` because of `nix doctor` is a blocker.

@srid On my MacOS and NixOS `nix doctor` seems to work even when `IN_NIX_SHELL` env is present. Any specific reason this check was added?

**Comment by shivaraj-bh** [comment]
For now, I can parse `direnv status` and check for the line `Found RC allowed true` to verify if direnv is allowed, in future parsing it from json would be better. ref: https://github.com/direnv/direnv/issues/244#issuecomment-520487528

**Comment by srid** [comment]
> @srid On my MacOS and NixOS `nix doctor` seems to work even when `IN_NIX_SHELL` env is present. Any specific reason this check was added?

Because it looks in PATH which is mutated by the nix shell,

<img width="457" alt="image" src="https://github.com/srid/nix-health/assets/3998/7045df6b-160d-4fdb-beec-008250c559ae">

**Comment by srid** [comment]
Perhaps instead of forcing the user to leave the nix shell, we can "undo" the nix shell environment somehow ...

**Comment by shivaraj-bh** [comment]
I might be wrong here, wouldn't it make sense for the test to fail when we add `pkgs.nix` in a `devShell` because then the user will be aware that there are two different versions of `nix` CLI in `PATH`? 

Correct me if I am wrong, but the test for "gcroots" and "client protocol matching store protocol" shouldn't be affected by mutated PATH by nix shell.

**Comment by srid** [comment]
> I might be wrong here, wouldn't it make sense for the test to fail when we add `pkgs.nix` in a `devShell` because then the user will be aware that there are two different versions of `nix` CLI in `PATH`?

Okay, that's a fair point.

**Comment by srid** [comment]
> Is it possible to also check if `direnv allow` has been run for the respective project/repo?

We can do this generically as part of https://github.com/juspay/nix-browser/issues/60#issue-1890933388

**Comment by srid** [comment]
I think this check should be disabled by default, and only enabled when `nix-health.default.direnv.enable = true;` is in the flake (per #60).

It should check:
- `direnv` is in PATH, else point to https://zero-to-flakes.com/direnv/
- `direnv status` contains `Found RC allowed true`, else ask the user to run `direnv allow`

This is enough to use this check in nammayatri.

I'll update the description accordingly.

**Comment by srid** [comment]
I'm gonna move this to `nix-browser` repo.

**Comment by srid** [comment]
https://github.com/juspay/nix-browser/issues/70
